### ISSUE TITLE
Multiple items with same display name.

### ISSUE THREAD

**Issue by PauMAVA** [feather-rs/libcraft#14]
So yes, Mojang is trolling us😄. Multiple items with the same display name.

The multiple banner patterns in Minecraft are distinguished as different items but have the same generic display name.

This renders the function `from_display_name(display_name: &str) -> Option<Self>` in the `Item` enum buggy. 

```rust
...
"Suspicious Stew" => Some(Item::SuspiciousStew),
"Loom" => Some(Item::Loom),
"Banner Pattern" => Some(Item::FlowerBannerPattern),
"Banner Pattern" => Some(Item::CreeperBannerPattern),
"Banner Pattern" => Some(Item::SkullBannerPattern),
"Banner Pattern" => Some(Item::MojangBannerPattern),
"Banner Pattern" => Some(Item::GlobeBannerPattern),
"Banner Pattern" => Some(Item::PiglinBannerPattern),
"Composter" => Some(Item::Composter),
"Barrel" => Some(Item::Barrel),
...
```

**EXAMPLE**
* The Player has an item of type `skull_banner_pattern`. 
* The developer gets the item's display name.
* The Developer tries to get the `Item` from the display name via `from_display_name(display_name: &str) -> Option<Self>`.
* The Developer gets `Item::FlowerBannerPattern` as `"Banner Pattern"` first matches with `Item::FlowerBannerPattern` in the match clause.

These names are the ones used in vanilla or at least are the ones listed in `prismarinejs/minecraft-data` repo which should be the vanilla ones.

![imagen](https://user-images.githubusercontent.com/36012050/109281977-3dbb4580-781d-11eb-8ee6-91c7ed25dc51.png)

This issue is intended to discuss and ask for possible workarounds on this.

**Comment by kallekankaanpaa** [comment]
@caelunshun Do you have any planned use-cases for the `from_display_name`  function?

**Comment by Schuwi** [comment]
Well unless we want to implement some kind of natural language parsing I would argue that a function `from_display_name` doesn't make sense in the first place.
The display name isn't guaranteed any stability, nor is it unique, nor does the naming has to follow any rules about which characters to use (e.g. capitalization). This name is purely intended to be displayed to humans, not to be interpreted by us.
